INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 369;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 921 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 413;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 100;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 99;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 16;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 830;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1250 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 369;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1928 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 369;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1879 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 368;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 888 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 369;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 891 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 414;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 413;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 620;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1267 AND e.caren_id = 18;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 901 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 901 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 901 AND e.caren_id = 369;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 901 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 901 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 901 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 901 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 901 AND e.caren_id = 620;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 901 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 901 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 901 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 901 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 368;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1749 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 414;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 413;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1627 AND e.caren_id = 18;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 414;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 413;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 620;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1109 AND e.caren_id = 18;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 414;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 413;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1106 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 413;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 620;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 909 AND e.caren_id = 18;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 369;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 903 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 369;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1595 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 369;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1745 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 368;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 1405;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 1407;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 620;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1992 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 369;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 1405;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 1407;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 620;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1868 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 368;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1362 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 368;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 894 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 414;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 413;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1772 AND e.caren_id = 18;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 414;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 413;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1771 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 414;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 413;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 896 AND e.caren_id = 18;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1593 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1593 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1593 AND e.caren_id = 369;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1593 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1593 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1593 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1593 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1593 AND e.caren_id = 620;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1593 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1593 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1593 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 1593 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 367;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 368;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 887 AND e.caren_id = 9;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 366;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 414;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 413;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 624;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 8;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 167;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 14;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 13;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 1037;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 11;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 10;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 12;
INSERT INTO car_extra (car_id, extra_id) SELECT c.car_id, e.extra_id FROM caren_cars c JOIN caren_extras e ON c.caren_id = 899 AND e.caren_id = 9;

-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (21,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (23,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (19,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (16,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (10,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,1);


-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,2);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,2);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,2);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,2);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,2);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,2);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,2);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,2);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (14,2);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (14,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,2);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (10,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (14,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (10,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (14,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (14,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (10,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (14,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,20);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,20);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,20);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,20);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,20);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,20);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,20);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,20);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,20);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,20);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (10,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (16,22);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (10,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (10,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,25);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (1,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (3,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (4,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (5,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (2,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (7,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (9,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (11,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (12,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (15,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (14,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (14,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (14,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (14,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,2);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (18,4);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (18,5);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (18,6);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (18,7);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (18,9);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (18,10);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (18,8);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,16);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,19);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,17);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,21);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,24);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (18,26);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (18,27);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (8,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,11);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,12);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,13);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,14);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,15);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,18);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,23);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,2);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,3);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,28);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (13,20);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (17,20);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (14,1);
-- INSERT INTO `car_extra` (`extra_id`,`car_id`) VALUES (14,20);
