<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="widtd=device-widtd, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>PDF</title>

        <!-- Styles -->     
        <link rel="stylesheet" href="{{ asset('css/print.css') }}">
        {{-- README: the dompdf library does not support flex, grid and other css 3 styles generated by tailwind --}}
    </head>

    <body>
        <div class="page">
            {{-- Logo & Details --}}
            <div class="h-14 relative w-full">
                <div class="absolute top-3 left-0">
                    <div class="font-fredokaOne text-pink-red font-normal text-2xl leading-9">Iceland Cars</div>                    
                </div>

                <div class="absolute top-0 left-52 text-xs">
                    <div class="font-bold mb-1">
                    Iceland Cars
                    </div>
                    
                    <div class="mb-1">
                    +354 5390605 - info@icelandcars.is - www.icelandcars.is
                    </div>
                    
                    <div>
                    Travel to Iceland ehf. - Flugvellir 6, 230 Keflavik (Iceland) - SSN: 680513-1630
                    </div>
                </div>
            </div>

            <hr class="bg-black h-0.5 my-4">

            <div class="text-center text-xl font-bold">
                Thank you for booking witd Iceland Cars
            </div>

            <div class="mt-4 text-lg font-bold">
                Booking Reference: {{ $booking->order_id }}
            </div>

            {{-- Data table --}}
            <div class="mt-4">
                <table class="min-w-full divide-y divide-gray-200 text-xs">
                    <tr class="border bg-gray-50">
                        <th class="w-1/3 border-r p-1 text-left">
                            Vehicle
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->car->name}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-100">
                        <th class="w-1/3 text-left border-r p-1">
                            From
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->pickup_at->format('d-m-Y H:i')}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-50">
                        <th class="w-1/3 text-left border-r p-1">
                            To
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->dropoff_at->format('d-m-Y H:i')}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-100">
                        <th class="w-1/3 text-left border-r p-1">
                            Pickup point details
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->pickupLocation->name}}
                            @if ($booking->pickup_input_info)
                                - {{$booking->pickup_input_info}}
                            @endif
                        </td>
                    </tr>

                    <tr class="border bg-gray-50">
                        <th class="w-1/3 text-left border-r p-1">
                            Dropoff point details
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->dropoffLocation->name}}
                            @if ($booking->dropoff_input_info)
                                - {{$booking->dropoff_input_info}}
                            @endif
                        </td>
                    </tr>

                    <tr class="border bg-gray-100">
                        <th class="w-1/3 text-left border-r p-1">
                            Name
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->first_name}} {{$booking->last_name}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-50">
                        <th class="w-1/3 text-left border-r p-1">
                            Email
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->email}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-100">
                        <th class="w-1/3 text-left border-r p-1">
                            Address
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->address}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-50">
                        <th class="w-1/3 text-left border-r p-1">
                            Zip / Postal Code
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->postal_code}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-100">
                        <th class="w-1/3 text-left border-r p-1">
                            City
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->city}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-50">
                        <th class="w-1/3 text-left border-r p-1">
                            Country
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->country}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-100">
                        <th class="w-1/3 text-left border-r p-1">
                            Telephone
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->telephone}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-50">
                        <th class="w-1/3 text-left border-r p-1">
                            Number of passengers
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->number_passengers}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-100">
                        <th class="w-1/3 text-left border-r p-1">
                            Driver's name
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->driver_name}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-50">
                        <th class="w-1/3 text-left border-r p-1">
                            Driver's license number
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->driver_license_number}}
                        </td>
                    </tr>

                    <tr class="border bg-gray-100">
                        <th class="w-1/3 text-left border-r p-1">
                            Driver's date of birtd
                        </th>

                        <td class="w-2/3  p-1">
                            {{$booking->driver_date_birtd}}
                        </td>
                    </tr>
                </table>
            </div>

            <div class="mt-8 text-xl font-bold">
                Payment
            </div>

            {{-- Payment table --}}
            <table class="mt-4 divide-y divide-gray-200 text-xs">
                <tr class="bg-white border">
                    <td class="p-1 w-52">
                        Total price
                    </td>

                    <td class="font-bold text-right p-1">
                        {{ formatPrice($booking->total_price, "ISK") }}
                    </td>
                </tr>

                <tr class="bg-white border">
                    <td class="p-1">
                        Online payment
                    </td>

                    <td class="font-bold text-right p-1">
                        {{ formatPrice($booking->online_payment, "ISK") }}
                    </td>
                </tr>

                <tr class="bg-white border">
                    <td class="p-1">
                        Pay in Iceland
                    </td>

                    <td class="font-bold text-right p-1">
                        {{ formatPrice(($booking->total_price - $booking->online_payment), "ISK") }}
                    </td>
                </tr>
            </table>

            <div class="mt-4 text-lg font-bold">
                Provided by
            </div>

            <div class="mt-2">
                @if ($booking->vendor->featured_image_url)
                    <img src="{{$booking->vendor->featured_image_url}}" class="w-40">
                @else
                    {{$booking->vendor->name}}
                @endif
            </div>

            <div class="mt-4 text-lg font-bold">
                Additional information
            </div>

            <div class="mt-2">
                <ul class="list-disc ml-4 text-xs">
                    <li class="ml-4">ID or passport of tde renter *</li>
                    <li class="ml-4">Valid driving license of tde driver (at least one year old) *</li>
                    <li class="ml-4">Valid credit card</li>
                </ul>
            </div>

            <div class="mt-2 text-xs">
                (*) Applicable to all additional drivers.
            </div>
        </div>
    </body>
</html>
